### ISSUE TITLE
[ROS1] Arrays of parameter maps are not supported

### ISSUE THREAD

**Issue by achim-k** [foxglove/ros-foxglove-bridge#219]
**Description**
See also #217 

```
inputs:
  - topic: /gps/fix
    message_type: NavSatFix
  - topic: /gps2/fix
    message_type: NavSatFix
  - topic: /gps3/fix
    message_type: NavSatFix
```

If the above parameter `inputs` is present, foxglove bridge logs the following error: `Unsupported parameter array type`

**Steps To Reproduce**
- Copy the above yaml into `params.yaml`
- `rosparam load params.yaml`
- Launch foxglove_bridge and connect with Foxglove Studio

**Expected Behavior**
All parameter types should be supported
